# Generated by Django 4.0.5 on 2022-06-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stage7', '0002_alter_hotel_recorde_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_recorde',
            name='number_of_night',
            field=models.IntegerField(),
        ),
    ]
